### ISSUE TITLE
Uncaught Error: Command failed: perl $ATOM_HOME/packages\pg-formatter\node_modules\pg-formatter\d...

### ISSUE THREAD

**Issue by ggada** [alexfedoseev/atom-pg-formatter#1]
1. Download atom on windows
2. Install this package
3. Select SQL code and `Control + Alt + S`

I have strawberry perl installed and it is in %PATH%

**Atom**: 1.21.2 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [pg-formatter](https://github.com/alexfedoseev/atom-pg-formatter) package 0.0.1

### Stack Trace

Uncaught Error: Command failed: perl C:\Users\gauragad\.atom\packages\pg-formatter\node_modules\pg-formatter\dist\pg-formatter\pg_format --function-case 0 --keyword-case 0 --spaces 4
'perl' is not recognized as an internal or external command,
operable program or batch file.

```
At child_process.js:545

Error: Command failed: perl C:\Users\gauragad\.atom\packages\pg-formatter\node_modules\pg-formatter\dist\pg-formatter\pg_format --function-case 0 --keyword-case 0 --spaces 4
'perl' is not recognized as an internal or external command,
operable program or batch file.

    at checkExecSyncError (child_process.js:502:13)
    at execSync (child_process.js:542:13)
    at childProcess.(anonymous function) (ELECTRON_ASAR.js:685:22)
    at exports.default (/packages/pg-formatter/node_modules/pg-formatter/dist/format.js:90:44)
    at Object.formatSource (/packages/pg-formatter/lib/index.js:65:27)
    at /packages/pg-formatter/lib/index.js:40:40
    at Array.forEach (native)
    at Object.triggerFormat (/packages/pg-formatter/lib/index.js:40:12)
    at HTMLElement.pgFormatterFormat (/packages/pg-formatter/lib/index.js:17:43)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.21.2/resources/app/src/command-registry.js:381:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.21.2/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.21.2/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.21.2/resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (~/AppData/Local/atom/app-1.21.2/resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -3:01.0 application:open-file (atom-pane.pane.active)
     -2:49.3.0 core:select-all (input.hidden-input)
     -2:48.4.0 pg-formatter:format (input.hidden-input)
```

### Non-Core Packages

```
language-pgsql 0.2.3 
pg-formatter 0.0.1 
```

**Comment by alex35mil** [comment]
Hey, sorry, but I don't have windows machine to debug it. Do you open your atom from terminal via `atom` command or by clicking icon from OS GUI? If the latter, then try the former so editor is able to infer `PATH` from your shell.

**Comment by ggada** [comment]
Let me give this a shot tomorrow and get back! I don't access to that machine right now

**Comment by ggada** [comment]
It works now! Is it possible to add some package setting to change the formatter behavior? Say like a checkbox for comma start/comma end option in pgFormatter

https://github.com/darold/pgFormatter


        Terminal/console execution
        Usage: pg_format [options] file.sql

        PostgreSQL SQL queries and PL/PGSQL code beautifier.

    Arguments:

        file.sql can be a file or use - to read query from stdin.

        Returning the SQL formatted to stdout or into a file specified with
        the -o | --ouput option.

    Options:

        -a | --anonymize      : obscure all literals in queries, useful to hide
                                confidential data before formatting.
        -b | --comma-start    : in a parameters list, start with the comma (see -e)
        -d | --debug          : enable debug mode. Disabled by default.
        -e | --comma-end      : in a parameters list, end with the comma (default)
        -f | --function-case N: Change the case of the reserved keyword. Default is
                                unchanged: 0. Values: 0=>unchanged, 1=>lowercase,
                                2=>uppercase, 3=>capitalize.
        -F | --format STR     : output format: text or html. Default: text.
        -h | --help           : show this message and exit.
        -m | --maxlength SIZE : maximum length of a query, it will be cutted above
                                the given size. Default: no truncate.
        -n | --nocomment      : remove any comment from SQL code.
        -o | --output file    : define the filename for the output. Default: stdout.
        -p | --placeholder re : set regex to find code that must not be changed.
        -s | --spaces size    : change space indent, default 4 spaces.
        -S | --separator STR  : dynamic code separator, default to single quote.
        -u | --keyword-case N : Change the case of the reserved keyword. Default is
                                uppercase: 2. Values: 0=>unchanged, 1=>lowercase,
                                2=>uppercase, 3=>capitalize.
        -v | --version        : show pg_format version and exit.

    Examples:

        cat samples/ex1.sql | pg_format -
        pg_format -n samples/ex1.sql
        pg_format -f 2 -n -o result.sql samples/ex1.sql

**Comment by rodsilva01** [comment]
@ggada Hello
I'm actually facing the same issue, saw that you were able to make it work, how did you do it?
Thank you!

**Comment by aharonh** [comment]
> @ggada Hello
> I'm actually facing the same issue, saw that you were able to make it work, how did you do it?
> Thank you!

Just install perl language support. You may fetch it from http://strawberryperl.com/
